# Netlify Configuration for Multi-Tenant E-commerce Platform

[build]
  base = "/"
  publish = "deploy"
  command = """
    npm ci &&
    npm run build --workspace=apps/shell &&
    npm run build --workspace=apps/storefront &&
    npm run build --workspace=apps/catalog &&
    npm run build --workspace=apps/orders &&
    npm run build --workspace=apps/analytics &&
    mkdir -p deploy &&
    cp -r apps/shell/dist/* deploy/ &&
    mkdir -p deploy/storefront deploy/catalog deploy/orders deploy/analytics &&
    cp -r apps/storefront/dist/* deploy/storefront/ &&
    cp -r apps/catalog/dist/* deploy/catalog/ &&
    cp -r apps/orders/dist/* deploy/orders/ &&
    cp -r apps/analytics/dist/* deploy/analytics/
  """

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for micro-frontend loading
[[headers]]
  for = "*.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    
[[headers]]
  for = "/storefront/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    
[[headers]]
  for = "/catalog/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    
[[headers]]
  for = "/orders/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    
[[headers]]
  for = "/analytics/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
